### ISSUE TITLE
What is the difference of this to iBiblia? 

### ISSUE THREAD

**Issue by SalitaNgDiyos** [rubiot/theword-addstrongs#1]
Can this automatically add strongs numbers and Morph Codes to a Greek NT Module or Hebrew OT module for theWord?

**Comment by rubiot** [comment]
This program copies tags from a tagged Bible module to an untagged one by looking for identical/similar words. Thus, this only works if both modules are in the same language and are similar translations/editions. I've used this sucessfully in some scenarios:

- Copy tags from one Greek edition to another very similar one. Worked perfectly, because, technically all major Greek NT editions are very much similar.
- Copy tags from on Portuguese translation to another. In this case the results will vary much, depending on the similarity between the translations. In my case, I'd say it associated something around 70% of the words. The program also gives you the option to generate a pre-associated iBiblia project, so what was left to do was the reviewing of the automatic associations and the association of the unmatched words the program couldn't associate. This was a pretty good kick-start for the project.

**Comment by SalitaNgDiyos** [comment]
I'd like to try this one too. Remember I sent you an email where I was looking for a Tagged Greek Received Text, unfortunately the official version in theWord website doesn't load the tags on my iBiblia probably due to the verse rules or something. I bet this will be much compatible to iBiblia since they're siblings. I feel that I need to tag using the Greek Text more than the KJV's strongs. I'm discovering some Greek words that are tagged multiple times in a sentence even though its just one Greek word in the original. And a lot of instances the Strongs number G3588 which are in the Greek is missing in the KJV!

**Comment by rubiot** [comment]
> I feel that I need to tag using the Greek Text more than the KJV's strongs.

It makes much more sense. You can work alongside with an interlinear (like TRi) if necessary.
> I'm discovering some Greek words that are tagged multiple times in a sentence even though its just one Greek word in the original.

Yes, those must be the instances in which a single Greek work is translated into multiple English words.

> And a lot of instances the Strongs number G3588 which are in the Greek is missing in the KJV!

Many parts of speech usually are not tagged. For instance, articles, prepositions, and conjunctions. I guess that's because people usually do work studies only on verbs, nouns, adjectives, etc. And, of course, it simplifies the tagging work.

> I'd like to try this one too.

You won't need this program for what you want. I can send you a working Scrivener's module (the base Greek text for KJV). I can do it when I get home.

**Comment by SalitaNgDiyos** [comment]
Thanks for your thoughtfulness, brother!

**Comment by SalitaNgDiyos** [comment]
Can this be used with these modules?
1. https://github.com/openbibles/LXX-Strongs-and-RMA-Codes/releases/download/1.000/LXX+.ot (strongs+morph+lxx w/o accents)
2. https://github.com/openbibles/LXX-Strongs-and-RMA-Codes/blob/master/lxxmorph-rc.zip (morph+lxx w/ accents)

**Comment by rubiot** [comment]
Yes, of course. I'll try and to that. I anticipate some versification discrepancies, though. Let's see.

**Comment by SalitaNgDiyos** [comment]
That's fine. I thought it was better to have an accented Greek Text than non-accented for our Greek speaking users.

**Comment by SalitaNgDiyos** [comment]
> 
> 
> Yes, of course. I'll try and to that. I anticipate some versification discrepancies, though. Let's see.

For Hebrew OT, yes, but since the two LXX texts I linked above are identical, there should be no discrepancy in the verses, I assume.

**Comment by SalitaNgDiyos** [comment]
> 
> 
> Can this be used with these modules?
> 
>     1. https://github.com/openbibles/LXX-Strongs-and-RMA-Codes/releases/download/1.000/LXX+.ot (strongs+morph+lxx w/o accents)
> 
>     2. https://github.com/openbibles/LXX-Strongs-and-RMA-Codes/blob/master/lxxmorph-rc.zip (morph+lxx w/ accents)

I just realized that the "auto-associate" in iBiblia does almost the same job as this one. I won't be needing this module since I've gotten a better one from Brenton's Edition.

**Comment by rubiot** [comment]
OK, I ended up running the script and, for my surprise the texts are mostly identical, differing only on verses that have versification markings. So, if you still want to merge these, you'd have make sure those verses are aligned in both modules.

**Comment by SalitaNgDiyos** [comment]
I think because it has the same source. I just started to tag the new LXX I sent you in my email from mathetes which was the source of Brenton's translation. There are a lot of variations in letters and verse divisions compared w/ Ralph's/CCAT versions. If you can apply this to that then we can have a way to tag Brenton's Translation in the future as well.

**Comment by SalitaNgDiyos** [comment]
> 
> 
> OK, I ended up running the script and, for my surprise the texts are mostly identical, differing only on verses that have versification markings. So, if you still want to merge these, you'd have make sure those verses are aligned in both modules.

I do have a question, though. Just in case you merge these two, is it possible to include the lemma codes in the exported file?

**Comment by rubiot** [comment]
All Strong's and morphology tags (including lemma, if present) are copied from the source module to the destination.
