### ISSUE TITLE
I don't know how it works

### ISSUE THREAD

**Issue by SalomoDavidson** [rubiot/theword-addstrongs#2]
I don't know how to code so I have no idea how this works. I also tried iBiblia,. but I don't know either how it works. I want to copy strongs from thye same language Bible to another. The only differences in the Bibles are that one has red text and the other doesn't and one has chapter titles.

Can someone help me please?

**Comment by rubiot** [comment]
Hello, friend. These Bibles have the exact same text? If so, both tools - thewordaddstrongs and iBiblia can help you. iBiblia should be simpler, but this requires some knowledge of how these tools work. If you don't mind, you can send me both modules and I can do it for you (send it to rubio.terra@gmail.com). Otherwise, tell me and I'll try and explain the process to you.

**Comment by rubiot** [comment]
I've received your files. Just to document it, here's what I did. First I had to convert both files to UTF-8. Then I ran the following command on Linux:
`./theword-addstrongs.p6 --file=dutsv.ont --borrow-from=DSV+ont | tee dutsv+ont`
I had to fix some wrong tags on the borrow-from module to get it to work.
